export const STRINGS = {
  en: {
    headerTitle: 'TARA ✦', langBadge: 'EN',
    chatPlaceholder: 'Ask me anything — products, prices, delivery…',
    sendBtn: 'Send', addToCart: 'Add to Cart',
    emptyProducts: "Tell me what you're looking for…",
    emptyProductsSub: "I'll find the best products for you.",
    welcomeMsg: "Hey! I'm TARA — your personal shopping agent for Kapruka 🛍️ Whether you're hunting for the perfect gift, sending love to family back home, or need something fast — just tell me what you're after!",
    typing: 'TARA is thinking', cartTitle: 'Your Cart', cartEmpty: 'Your cart is empty',
    checkout: 'Checkout', total: 'Total', removeItem: 'Remove',
    cartBtn: 'Cart', viewCart: 'View Cart', lkr: 'Rs.',
    viewOnKapruka: 'View on Kapruka →', addToCartModal: 'Add to Cart', closeModal: 'Close',
    quickChips: ['Find a gift 🎁', 'Browse Electronics 📱', 'Track my order 📦', 'Ordering from abroad? ✈️'],
    deliveryCity: 'Delivery City', deliveryCityPlaceholder: 'Type city name…',
    deliveryDate: 'Delivery Date', deliveryAvailable: 'Delivery available',
    deliveryUnavailable: 'Not deliverable to this city on that date',
    deliveryFee: 'Delivery fee', recipientSection: 'Recipient Details',
    addressLine1: 'Address Line 1', addressLine2: 'Address Line 2 (optional)',
    fullName: 'Full name', phone: 'Phone (+94xxxxxxxxx)',
    kaprukaSigning: 'Have a Kapruka account? Sign in →',
    guestCheckout: 'Or checkout as guest — no account needed.',
    inStock: 'In Stock', outOfStock: 'Out of Stock',
    reorderPrompt: 'Last time you ordered — want to reorder? 🔄',
    reorderBtn: 'Reorder in one tap', reorderAdded: 'Cart rebuilt! Choose a delivery date.',
    fathersDayHint: "Father's Day is this month 👨 — want to send something special to your thaththa?",
    orderSpeedPrefix: '✦ Order placed in', orderSpeedSuffix: '⚡ — faster than typing it yourself!',
  },
  si: {
    headerTitle: 'TARA ✦', langBadge: 'සිං',
    chatPlaceholder: 'ඔබ සොයන දේ අසන්න…',
    sendBtn: 'යවන්න', addToCart: 'කාට් එකට දාන්න',
    emptyProducts: 'ඔබ සොයන දේ කියන්න…', emptyProductsSub: 'හොඳම නිෂ්පාදන සොයා ගනිමි.',
    welcomeMsg: 'ආයුබෝවන්! 🙏 මම TARA — Kapruka හරහා ඔබේ AI shopping friend. ඔබට ඕනෑ දේ කියන්න — gift idea එකක්, groceries, electronics, හෝ family ට special දෙයක් — එකට හොයමු!',
    typing: 'TARA සිතමින් සිටී', cartTitle: 'ඔබේ කාට්', cartEmpty: 'කාට් හිස්ය',
    checkout: 'ගෙවන්න', total: 'මුළු', removeItem: 'ඉවත් කරන්න',
    cartBtn: 'කාට්', viewCart: 'කාට් බලන්න', lkr: 'රු.',
    viewOnKapruka: 'Kapruka හිදී බලන්න →', addToCartModal: 'කාට් එකට දාන්න', closeModal: 'වසන්න',
    quickChips: ['තෑගක් ගන්න 🎁', 'Electronics බලන්න 📱', 'Order track කරන්න 📦', 'විදේශයෙන් order කරනවාද? ✈️'],
    deliveryCity: 'බෙදාහැරීමේ නගරය', deliveryCityPlaceholder: 'නගරය ටයිප් කරන්න…',
    deliveryDate: 'බෙදාහැරීමේ දිනය', deliveryAvailable: 'බෙදාහැරීම ලබාගත හැකිය',
    deliveryUnavailable: 'ඒ දිනයේ බෙදාහැරීම නොමැත', deliveryFee: 'බෙදාහැරීමේ ගාස්තුව',
    recipientSection: 'ලැබෙන්නාගේ විස්තර', addressLine1: 'ලිපිනය 1',
    addressLine2: 'ලිපිනය 2 (අනිවාර්ය නොවේ)', fullName: 'සම්පූර්ණ නම',
    phone: 'දුරකථනය (+94xxxxxxxxx)', kaprukaSigning: 'Kapruka ගිණුමක් තිබේද? ඇතුළු වන්න →',
    guestCheckout: 'නැතිනම් ගිණුමකින් තොරව checkout කරන්න.',
    inStock: 'තොගයේ ඇත', outOfStock: 'නොමැත',
    reorderPrompt: 'ඉකුත්වර ඔබ order කළ දේ නැවත order කරනවද? 🔄',
    reorderBtn: 'නැවත order කරන්න', reorderAdded: 'කාට් සකස් කළා! දිනයක් තෝරන්න.',
    fathersDayHint: 'මේ මාසේ තාත්තාගේ දිනයයි 👨 — ඔබේ තාත්තාට විශේෂ දෙයක් යැවිය හැකිද?',
    orderSpeedPrefix: '✦ Order දුන්නේ', orderSpeedSuffix: '⚡ — ඉක්මනින්!',
  },
  // Sihalish — romanized Sinhala + English. How Sri Lankans actually WhatsApp.
  sl: {
    headerTitle: 'TARA ✦', langBadge: 'SL',
    chatPlaceholder: 'Mokada ona kiyanna… (type what you need)',
    sendBtn: 'Send karanna', addToCart: 'Cart ekata denna',
    emptyProducts: 'Mokada ona kiyanna…', emptyProductsSub: 'Hondama eka hadanna.',
    welcomeMsg: 'Ayubowan! 🙏 Mama TARA — Kapruka eken oya hoyanawa hariyata! Mokada ganna ona kiyanna — gift, food, electronics, family ata special deyek — hadamu baramu!',
    typing: 'TARA hithana wela inna', cartTitle: 'Cart eka', cartEmpty: 'Cart eka empty',
    checkout: 'Pay karanna', total: 'Total', removeItem: 'Araganna',
    cartBtn: 'Cart', viewCart: 'Cart eka balanna', lkr: 'Rs.',
    viewOnKapruka: 'Kapruka waladi balanna →', addToCartModal: 'Cart ekata denna', closeModal: 'Whasanna',
    quickChips: ['Hadiyak ganna 🎁', 'Electronics balanna 📱', 'Order track karanna 📦', 'Wideshayen order karannada? ✈️'],
    deliveryCity: 'Deliver wenawa koheda?', deliveryCityPlaceholder: 'Town eka type karanna…',
    deliveryDate: 'Deliver wenna one dina eka', deliveryAvailable: 'Deliver karanna puluwan',
    deliveryUnavailable: 'E dina e town ekata deliver karanna ne', deliveryFee: 'Delivery ganu dena eka',
    recipientSection: 'Labena minihage details', addressLine1: 'Address 1',
    addressLine2: 'Address 2 (one nam)', fullName: 'Pura nama', phone: 'Phone (+94xxxxxxxxx)',
    kaprukaSigning: 'Kapruka account thibba da? Sign in wenawa →',
    guestCheckout: 'Nathnam account nathuwama checkout karanna.',
    inStock: 'Thiyanawa', outOfStock: 'Nehe',
    reorderPrompt: 'Kalin order ekak dunna — nawa ekak gamu da? 🔄',
    reorderBtn: 'Nawa order karanna', reorderAdded: 'Cart eka hadala! Dina eka thoro ganna.',
    fathersDayHint: 'Me maase thaththa ge dina 👨 — thaththa ta mokak hari yawamu da?',
    orderSpeedPrefix: '✦ Order dunne', orderSpeedSuffix: '⚡ — wada igenma!',
  },
  ta: {
    headerTitle: 'TARA ✦', langBadge: 'தமிழ்',
    chatPlaceholder: 'நீங்கள் தேடுவதை கேளுங்கள்…',
    sendBtn: 'அனுப்பு', addToCart: 'கார்ட்டில் சேர்',
    emptyProducts: 'நீங்கள் தேடுவதை சொல்லுங்கள்…', emptyProductsSub: 'சிறந்த தயாரிப்புகளை கண்டுபிடிக்கிறேன்.',
    welcomeMsg: 'வணக்கம்! 🙏 நான் TARA — Kapruka-வின் உங்கள் AI shopping friend. பரிசு வேணுமா, groceries வேணுமா, அல்லது வீட்டில் உள்ளவர்களுக்கு ஏதாவது அனுப்பணுமா — சொல்லுங்கள், தேடுவோம்!',
    typing: 'TARA யோசிக்கிறது', cartTitle: 'உங்கள் கார்ட்', cartEmpty: 'கார்ட் காலியாக உள்ளது',
    checkout: 'பணம் செலுத்து', total: 'மொத்தம்', removeItem: 'நீக்கு',
    cartBtn: 'கார்ட்', viewCart: 'கார்ட் பார்', lkr: 'Rs.',
    viewOnKapruka: 'Kapruka-ல் பார் →', addToCartModal: 'கார்ட்டில் சேர்', closeModal: 'மூடு',
    quickChips: ['பரிசு கண்டுபிடி 🎁', 'Electronics பார் 📱', 'Order track செய் 📦', 'வெளிநாட்டில் இருக்கீங்களா? ✈️'],
    deliveryCity: 'டெலிவரி நகரம்', deliveryCityPlaceholder: 'நகரம் தட்டச்சு செய்யுங்கள்…',
    deliveryDate: 'டெலிவரி தேதி', deliveryAvailable: 'டெலிவரி கிடைக்கும்',
    deliveryUnavailable: 'அந்த தேதியில் டெலிவரி இல்லை', deliveryFee: 'டெலிவரி கட்டணம்',
    recipientSection: 'பெறுபவர் விவரங்கள்', addressLine1: 'முகவரி வரி 1',
    addressLine2: 'முகவரி வரி 2 (விரும்பினால்)', fullName: 'முழு பெயர்',
    phone: 'தொலைபேசி (+94xxxxxxxxx)', kaprukaSigning: 'Kapruka கணக்கு உள்ளதா? உள்நுழைக →',
    guestCheckout: 'அல்லது கணக்கில்லாமல் checkout செய்யலாம்.',
    inStock: 'கையிருப்பில் உள்ளது', outOfStock: 'இல்லை',
    reorderPrompt: 'முன்பு ஆர்டர் செய்தீர்களா? மீண்டும் ஆர்டர் செய்யலாமா? 🔄',
    reorderBtn: 'மீண்டும் ஆர்டர் செய்', reorderAdded: 'கார்ட் தயார்! தேதி தேர்ந்தெடுக்கவும்.',
    fathersDayHint: 'இந்த மாதம் தந்தையர் தினம் 👨 — உங்கள் அப்பாவிற்கு ஏதாவது அனுப்பலாமா?',
    orderSpeedPrefix: '✦ Order செய்யப்பட்டது', orderSpeedSuffix: '⚡ — வேகமாக!',
  },
  tl: {
    headerTitle: 'TARA ✦', langBadge: 'TL',
    chatPlaceholder: 'Machan, ask me ethuvaanalum…',
    sendBtn: 'Send la', addToCart: 'Add to Cart',
    emptyProducts: 'Enna venum endu sollunga…', emptyProductsSub: 'Kandu Pidithu tharukiren, machann.',
    welcomeMsg: "Vanakam machan! 👋 I'm TARA — Kapruka-la unga personal shopping friend! Gift venuma, food venuma, electronics venuma, family-ku enna anupanumna — solunga, kandupidikrom!",
    typing: 'TARA thinking la', cartTitle: 'Your Cart la', cartEmpty: 'Cart empty la',
    checkout: 'Pay now la', total: 'Total', removeItem: 'Remove',
    cartBtn: 'Cart', viewCart: 'See Cart', lkr: 'Rs.',
    viewOnKapruka: 'View on Kapruka la →', addToCartModal: 'Add to Cart la', closeModal: 'Close la',
    quickChips: ['Gift anuppa 🎁', 'Electronics paaka 📱', 'Order track pannanuma 📦', 'Foreign la irunthu order pannanuma? ✈️'],
    deliveryCity: 'Enga deliver pannanum?', deliveryCityPlaceholder: 'Type city la…',
    deliveryDate: 'Deliver panna vendiya date', deliveryAvailable: 'Deliver panna mudiyum la',
    deliveryUnavailable: 'Antha date-ku deliver illa la', deliveryFee: 'Delivery charges',
    recipientSection: 'Vaanguravanga details', addressLine1: 'Address line 1',
    addressLine2: 'Address line 2 (venum na la)', fullName: 'Full name', phone: 'Phone (+94xxxxxxxxx)',
    kaprukaSigning: 'Kapruka account irukaa? Sign in la →',
    guestCheckout: 'Illana account illamale checkout pannunga la.',
    inStock: 'Iruku', outOfStock: 'Illa la',
    reorderPrompt: 'Last time order panninga — reorder pannuvoma la? 🔄',
    reorderBtn: 'Reorder pannunga la', reorderAdded: 'Cart ready la! Date select pannunga machang.',
    fathersDayHint: "Intha maasam Father's Day la 👨 — appaku ethachum anuppuvoma?",
    orderSpeedPrefix: '✦ Order panni', orderSpeedSuffix: '⚡ — semma fast la!',
  },
};

export type Lang = keyof typeof STRINGS;

export function detectLang(t: string): Lang {
  if (/[\u0D80-\u0DFF]/.test(t)) return 'si';
  if (/[\u0B80-\u0BFF]/.test(t)) return 'ta';
  if (/\b(machang|machan|aiyo|oneda|aney|yako)\b/i.test(t)) return 'tl';
  if (/\b(la|neh|ne|da)\s*[.!?,]?\s*$/im.test(t.trim())) return 'tl';
  // Sihalish — romanized Sinhala (must check before English default)
  if (/\b(mama|api|eka|ekak|ona|nehe|koheda|mokada|puluwan|bohoma|hariyata|hadanna|karanna|balanna|ganna|denna|yanawa|thiyenawa|gedara|amma|thaththa|akka|aiya|nangi|malli|hondai|hari|tika|godak|wela|isthuti|ayubowan|subha)\b/i.test(t)) return 'sl';
  return 'en';
}
