export const STRINGS = {
  en: {
    headerTitle: 'TARA ✦',
    langBadge: 'EN',
    chatPlaceholder: 'Ask me anything — products, prices, delivery…',
    sendBtn: 'Send',
    addToCart: 'Add to Cart',
    emptyProducts: 'Tell me what you\'re looking for…',
    emptyProductsSub: 'I\'ll find the best products for you.',
    welcomeMsg: 'Hello! 👋 I\'m TARA, your AI shopping assistant. What are you looking for today?',
    typing: 'TARA is thinking',
    cartTitle: 'Your Cart',
    cartEmpty: 'Your cart is empty',
    checkout: 'Checkout',
    total: 'Total',
    removeItem: 'Remove',
    cartBtn: 'Cart',
    viewCart: 'View Cart',
    lkr: 'LKR',
    viewOnKapruka: 'View on Kapruka →',
    addToCartModal: 'Add to Cart',
    closeModal: 'Close',
    quickChips: ['Find a gift 🎁', 'Browse Electronics 📱', 'Track my order 📦'],
    deliveryCity: 'Delivery City',
    deliveryCityPlaceholder: 'Type city name…',
    deliveryDate: 'Delivery Date',
    deliveryAvailable: 'Delivery available',
    deliveryUnavailable: 'Not deliverable to this city on that date',
    deliveryFee: 'Delivery fee',
    recipientSection: 'Recipient Details',
    addressLine1: 'Address Line 1',
    addressLine2: 'Address Line 2 (optional)',
    fullName: 'Full name',
    phone: 'Phone (+94xxxxxxxxx)',
    kaprukaSigning: 'Have a Kapruka account? Sign in →',
    guestCheckout: 'Or checkout as guest below — no account needed.',
    inStock: 'In Stock',
    outOfStock: 'Out of Stock',
  },
  si: {
    headerTitle: 'TARA ✦',
    langBadge: 'සිං',
    chatPlaceholder: 'ඔබ සොයන දේ අසන්න…',
    sendBtn: 'යවන්න',
    addToCart: 'කාට් එකට දාන්න',
    emptyProducts: 'ඔබ සොයන දේ කියන්න…',
    emptyProductsSub: 'හොඳම නිෂ්පාදන සොයා ගනිමි.',
    welcomeMsg: 'ආයුබෝවන්! 🙏 මම TARA. ඔබට අවශ්‍ය දේ කියන්න.',
    typing: 'TARA සිතමින් සිටී',
    cartTitle: 'ඔබේ කාට්',
    cartEmpty: 'කාට් හිස්ය',
    checkout: 'ගෙවන්න',
    total: 'මුළු',
    removeItem: 'ඉවත් කරන්න',
    cartBtn: 'කාට්',
    viewCart: 'කාට් බලන්න',
    lkr: 'රු',
    viewOnKapruka: 'Kapruka හිදී බලන්න →',
    addToCartModal: 'කාට් එකට දාන්න',
    closeModal: 'වසන්න',
    quickChips: ['තෑගක් ගන්න 🎁', 'Electronics බලන්න 📱', 'Order track කරන්න 📦'],
    deliveryCity: 'බෙදාහැරීමේ නගරය',
    deliveryCityPlaceholder: 'නගරය ටයිප් කරන්න…',
    deliveryDate: 'බෙදාහැරීමේ දිනය',
    deliveryAvailable: 'බෙදාහැරීම ලබාගත හැකිය',
    deliveryUnavailable: 'ඒ දිනයේ බෙදාහැරීම නොමැත',
    deliveryFee: 'බෙදාහැරීමේ ගාස්තුව',
    recipientSection: 'ලැබෙන්නාගේ විස්තර',
    addressLine1: 'ලිපිනය 1',
    addressLine2: 'ලිපිනය 2 (අනිවාර්ය නොවේ)',
    fullName: 'සම්පූර්ණ නම',
    phone: 'දුරකථනය (+94xxxxxxxxx)',
    kaprukaSigning: 'Kapruka ගිණුමක් තිබේද? ඇතුළු වන්න →',
    guestCheckout: 'නැතිනම් ගිණුමකින් තොරව checkout කරන්න.',
    inStock: 'තොගයේ ඇත',
    outOfStock: 'නොමැත',
  },
  ta: {
    headerTitle: 'TARA ✦',
    langBadge: 'தமிழ்',
    chatPlaceholder: 'நீங்கள் தேடுவதை கேளுங்கள்…',
    sendBtn: 'அனுப்பு',
    addToCart: 'கார்ட்டில் சேர்',
    emptyProducts: 'நீங்கள் தேடுவதை சொல்லுங்கள்…',
    emptyProductsSub: 'சிறந்த தயாரிப்புகளை கண்டுபிடிக்கிறேன்.',
    welcomeMsg: 'வணக்கம்! 👋 நான் TARA, உங்கள் AI ஷாப்பிங் உதவியாளர். இன்று என்ன தேடுகிறீர்கள்?',
    typing: 'TARA யோசிக்கிறது',
    cartTitle: 'உங்கள் கார்ட்',
    cartEmpty: 'கார்ட் காலியாக உள்ளது',
    checkout: 'பணம் செலுத்து',
    total: 'மொத்தம்',
    removeItem: 'நீக்கு',
    cartBtn: 'கார்ட்',
    viewCart: 'கார்ட் பார்',
    lkr: 'ரூ',
    viewOnKapruka: 'Kapruka-ல் பார் →',
    addToCartModal: 'கார்ட்டில் சேர்',
    closeModal: 'மூடு',
    quickChips: ['பரிசு கண்டுபிடி 🎁', 'Electronics பார் 📱', 'Order track செய் 📦'],
    deliveryCity: 'டெலிவரி நகரம்',
    deliveryCityPlaceholder: 'நகரம் தட்டச்சு செய்யுங்கள்…',
    deliveryDate: 'டெலிவரி தேதி',
    deliveryAvailable: 'டெலிவரி கிடைக்கும்',
    deliveryUnavailable: 'அந்த தேதியில் டெலிவரி இல்லை',
    deliveryFee: 'டெலிவரி கட்டணம்',
    recipientSection: 'பெறுபவர் விவரங்கள்',
    addressLine1: 'முகவரி வரி 1',
    addressLine2: 'முகவரி வரி 2 (விரும்பினால்)',
    fullName: 'முழு பெயர்',
    phone: 'தொலைபேசி (+94xxxxxxxxx)',
    kaprukaSigning: 'Kapruka கணக்கு உள்ளதா? உள்நுழைக →',
    guestCheckout: 'அல்லது கணக்கில்லாமல் checkout செய்யலாம்.',
    inStock: 'கையிருப்பில் உள்ளது',
    outOfStock: 'இல்லை',
  },
  tl: {
    headerTitle: 'TARA ✦',
    langBadge: 'TL',
    chatPlaceholder: 'Machan, ask me anything la…',
    sendBtn: 'Send la',
    addToCart: 'Add to Cart',
    emptyProducts: 'Tell me what you need la…',
    emptyProductsSub: 'Will find the best for you, machang.',
    welcomeMsg: "Aiyo, hello! 👋 I'm TARA la, your AI shopping kaki. What you looking for today oneda?",
    typing: 'TARA thinking la',
    cartTitle: 'Your Cart la',
    cartEmpty: 'Cart empty la',
    checkout: 'Pay now la',
    total: 'Total',
    removeItem: 'Remove',
    cartBtn: 'Cart',
    viewCart: 'See Cart',
    lkr: 'LKR',
    viewOnKapruka: 'View on Kapruka la →',
    addToCartModal: 'Add to Cart la',
    closeModal: 'Close la',
    quickChips: ['Gift danna 🎁', 'Electronics balan 📱', 'Order track karanna 📦'],
    deliveryCity: 'Delivery city',
    deliveryCityPlaceholder: 'Type city la…',
    deliveryDate: 'Delivery date',
    deliveryAvailable: 'Delivery ok la',
    deliveryUnavailable: 'Cannot deliver la on that day',
    deliveryFee: 'Delivery fee',
    recipientSection: 'Recipient details',
    addressLine1: 'Address line 1',
    addressLine2: 'Address line 2 (optional la)',
    fullName: 'Full name',
    phone: 'Phone (+94xxxxxxxxx)',
    kaprukaSigning: 'Got Kapruka account? Sign in la →',
    guestCheckout: 'Or checkout without account la — no problem.',
    inStock: 'In stock',
    outOfStock: 'Out of stock',
  },
};

export type Lang = keyof typeof STRINGS;

export function detectLang(t: string): Lang {
  if (/[\u0D80-\u0DFF]/.test(t)) return 'si';
  if (/[\u0B80-\u0BFF]/.test(t)) return 'ta';
  if (/\b(machang|aiyo|oneda|aney|la$)\b/i.test(t)) return 'tl';
  return 'en';
}
