export const STRINGS = {
  en: {
    headerTitle: 'TARA ✦',
    langBadge: 'EN',
    chatPlaceholder: 'Ask me anything — products, prices, delivery…',
    sendBtn: 'Send',
    addToCart: 'Add to TARA',
    emptyProducts: 'Tell me what you\'re looking for…',
    emptyProductsSub: 'I\'ll find the best products for you.',
    welcomeMsg: 'Hello! 👋 I\'m TARA, your AI shopping assistant. What are you looking for today?',
    typing: 'TARA is thinking',
    cartTitle: 'Your Cart',
    cartEmpty: 'Your cart is empty',
    checkout: 'Checkout',
    total: 'Total',
    removeItem: 'Remove',
    cartBtn: 'Cart',
    viewCart: 'View Cart',
    lkr: 'LKR',
  },
  si: {
    headerTitle: 'TARA ✦',
    langBadge: 'සිං',
    chatPlaceholder: 'ඔබ සොයන දේ අසන්න…',
    sendBtn: 'යවන්න',
    addToCart: 'TARA ට එකතු කරන්න',
    emptyProducts: 'ඔබ සොයන දේ කියන්න…',
    emptyProductsSub: 'හොඳම නිෂ්පාදන සොයා ගනිමි.',
    welcomeMsg: 'ආයුබෝවන්! 👋 මම TARA, ඔබේ AI සාප්පු සහායක. අද ඔබ සොයන්නේ කුමක්ද?',
    typing: 'TARA සිතමින් සිටී',
    cartTitle: 'ඔබේ කාට්',
    cartEmpty: 'කාට් හිස්ය',
    checkout: 'ගෙවන්න',
    total: 'මුළු',
    removeItem: 'ඉවත් කරන්න',
    cartBtn: 'කාට්',
    viewCart: 'කාට් බලන්න',
    lkr: 'රු',
  },
  ta: {
    headerTitle: 'TARA ✦',
    langBadge: 'தமிழ்',
    chatPlaceholder: 'நீங்கள் தேடுவதை கேளுங்கள்…',
    sendBtn: 'அனுப்பு',
    addToCart: 'TARA இல் சேர்',
    emptyProducts: 'நீங்கள் தேடுவதை சொல்லுங்கள்…',
    emptyProductsSub: 'சிறந்த தயாரிப்புகளை கண்டுபிடிக்கிறேன்.',
    welcomeMsg: 'வணக்கம்! 👋 நான் TARA, உங்கள் AI ஷாப்பிங் உதவியாளர். இன்று என்ன தேடுகிறீர்கள்?',
    typing: 'TARA யோசிக்கிறது',
    cartTitle: 'உங்கள் கார்ட்',
    cartEmpty: 'கார்ட் காலியாக உள்ளது',
    checkout: 'பணம் செலுத்து',
    total: 'மொத்தம்',
    removeItem: 'நீக்கு',
    cartBtn: 'கார்ட்',
    viewCart: 'கார்ட் பார்',
    lkr: 'ரூ',
  },
  tl: {
    headerTitle: 'TARA ✦',
    langBadge: 'TL',
    chatPlaceholder: 'Machan, ask me anything la…',
    sendBtn: 'Send la',
    addToCart: 'Add to TARA',
    emptyProducts: 'Tell me what you need la…',
    emptyProductsSub: 'Will find the best for you, machang.',
    welcomeMsg: "Aiyo, hello! 👋 I'm TARA la, your AI shopping kaki. What you looking for today oneda?",
    typing: 'TARA thinking la',
    cartTitle: 'Your Cart la',
    cartEmpty: 'Cart empty la',
    checkout: 'Pay now la',
    total: 'Total',
    removeItem: 'Remove',
    cartBtn: 'Cart',
    viewCart: 'See Cart',
    lkr: 'LKR',
  },
};

export type Lang = keyof typeof STRINGS;

export function detectLang(t: string): Lang {
  if (/[\u0D80-\u0DFF]/.test(t)) return 'si';
  if (/[\u0B80-\u0BFF]/.test(t)) return 'ta';
  if (/\b(machang|aiyo|oneda|aney|la$)\b/i.test(t)) return 'tl';
  return 'en';
}
